// ══════════════════════════════════════════════════════════════
// FITPULSE — EXERCISE DATABASE v3
// Calisthenics / Street Workout / Bodyweight only
// ~65 exercises with XP weights and hold flags
// ══════════════════════════════════════════════════════════════

export const MUSCLE_INFO = {
  // ── CHEST ──
  pec_major_upper:   { sr: "Pectoralis major (gornji)", en: "Pectoralis major (upper)", group: "Grudi" },
  pec_major_lower:   { sr: "Pectoralis major (donji)",  en: "Pectoralis major (lower)", group: "Grudi" },
  pec_minor:         { sr: "Pectoralis minor",           en: "Pectoralis minor",         group: "Grudi" },
  serratus:          { sr: "Serratus anterior",          en: "Serratus anterior",        group: "Grudi" },
  // ── BACK ──
  lats:              { sr: "Latissimus dorsi",           en: "Latissimus dorsi",         group: "Leđa" },
  trap_upper:        { sr: "Trapezius (gornji)",         en: "Trapezius (upper)",        group: "Leđa" },
  trap_mid:          { sr: "Trapezius (srednji)",        en: "Trapezius (middle)",       group: "Leđa" },
  trap_lower:        { sr: "Trapezius (donji)",          en: "Trapezius (lower)",        group: "Leđa" },
  rhomboids:         { sr: "Rhomboids",                  en: "Rhomboids",                group: "Leđa" },
  teres_major:       { sr: "Teres major",                en: "Teres major",              group: "Leđa" },
  teres_minor:       { sr: "Teres minor",                en: "Teres minor",              group: "Leđa" },
  infraspinatus:     { sr: "Infraspinatus",              en: "Infraspinatus",            group: "Leđa" },
  erector_spinae:    { sr: "Erector spinae",             en: "Erector spinae",           group: "Leđa" },
  // ── SHOULDERS ──
  delt_anterior:     { sr: "Deltoid (prednji)",          en: "Anterior deltoid",         group: "Ramena" },
  delt_lateral:      { sr: "Deltoid (bočni)",            en: "Lateral deltoid",          group: "Ramena" },
  delt_posterior:    { sr: "Deltoid (zadnji)",           en: "Posterior deltoid",        group: "Ramena" },
  // ── ARMS ──
  bicep_long:        { sr: "Biceps (duga glava)",        en: "Biceps (long head)",       group: "Ruke" },
  bicep_short:       { sr: "Biceps (kratka glava)",      en: "Biceps (short head)",      group: "Ruke" },
  brachialis:        { sr: "Brachialis",                 en: "Brachialis",               group: "Ruke" },
  brachioradialis:   { sr: "Brachioradialis",            en: "Brachioradialis",          group: "Ruke" },
  tricep_long:       { sr: "Triceps (duga glava)",       en: "Triceps (long head)",      group: "Ruke" },
  tricep_lateral:    { sr: "Triceps (lateralna)",        en: "Triceps (lateral head)",   group: "Ruke" },
  tricep_medial:     { sr: "Triceps (medijalna)",        en: "Triceps (medial head)",    group: "Ruke" },
  // ── CORE ──
  rectus_abdominis:  { sr: "Rectus abdominis",           en: "Rectus abdominis",         group: "Core" },
  oblique_ext:       { sr: "Obliquus externus",          en: "External oblique",         group: "Core" },
  oblique_int:       { sr: "Obliquus internus",          en: "Internal oblique",         group: "Core" },
  transversus:       { sr: "Transversus abdominis",      en: "Transversus abdominis",    group: "Core" },
  // ── LEGS ──
  rectus_femoris:    { sr: "Rectus femoris",             en: "Rectus femoris",           group: "Noge" },
  vastus_lat:        { sr: "Vastus lateralis",           en: "Vastus lateralis",         group: "Noge" },
  vastus_med:        { sr: "Vastus medialis",            en: "Vastus medialis",          group: "Noge" },
  vastus_int:        { sr: "Vastus intermedius",         en: "Vastus intermedius",       group: "Noge" },
  bicep_femoris:     { sr: "Biceps femoris",             en: "Biceps femoris",           group: "Noge" },
  semitendinosus:    { sr: "Semitendinosus",             en: "Semitendinosus",           group: "Noge" },
  semimembranosus:   { sr: "Semimembranosus",            en: "Semimembranosus",          group: "Noge" },
  glute_max:         { sr: "Gluteus maximus",            en: "Gluteus maximus",          group: "Noge" },
  glute_med:         { sr: "Gluteus medius",             en: "Gluteus medius",           group: "Noge" },
  glute_min:         { sr: "Gluteus minimus",            en: "Gluteus minimus",          group: "Noge" },
  gastrocnemius:     { sr: "Gastrocnemius",              en: "Gastrocnemius",            group: "Noge" },
  soleus:            { sr: "Soleus",                     en: "Soleus",                   group: "Noge" },
  iliopsoas:         { sr: "Iliopsoas",                  en: "Iliopsoas",                group: "Noge" },
};

// ── isHold: true → input treated as seconds, XP = seconds × xpWeight
// ── xpWeight: XP per rep (or XP per second for holds)
// ── difficulty: 1-10 cosmetic label
// ── category: push | pull | dips | legs | core | hold | skill

export const EXERCISE_DB = [

  // ══════════════════════════════════════════════════════════
  // PUSH
  // ══════════════════════════════════════════════════════════
  {
    id: "knee_pushup",
    sr: "Sklekovi na kolenima", en: "Knee Push-Up",
    icon: "🤸", category: "push", difficulty: 1,
    xpWeight: 0.5,
    desc_sr: "Modifikovana verzija skleka za početnike. Kolena na podu, fokus na formi.",
    desc_en: "Beginner push-up variation with knees on the floor.",
    muscles: { primary: ["pec_major_lower"], secondary: ["tricep_lateral","delt_anterior"] },
  },
  {
    id: "sklekovi_siroki",
    sr: "Sklekovi široki", en: "Wide Push-Up",
    icon: "🤸", category: "push", difficulty: 2,
    xpWeight: 1.5,
    desc_sr: "Ruke šire od ramena, naglasak na spoljašnjim grudima.",
    desc_en: "Hands wider than shoulder-width, outer chest emphasis.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","delt_anterior","serratus"] },
  },
  {
    id: "push_up",
    sr: "Sklekovi", en: "Push-Up",
    icon: "💪", category: "push", difficulty: 2,
    xpWeight: 1.0,
    desc_sr: "Osnovna vežba gornjeg dela tela. Telo u ravnoj liniji.",
    desc_en: "The foundational upper body exercise. Body in a straight line.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","tricep_lateral","delt_anterior","serratus"] },
  },
  {
    id: "sklekovi_uski",
    sr: "Sklekovi uski", en: "Close Push-Up",
    icon: "🤸", category: "push", difficulty: 3,
    xpWeight: 1.2,
    desc_sr: "Ruke bliže jedna drugoj, veći fokus na triceps.",
    desc_en: "Hands closer together, greater tricep activation.",
    muscles: { primary: ["tricep_long","tricep_lateral","tricep_medial"], secondary: ["pec_major_lower","delt_anterior"] },
  },
  {
    id: "sklekovi_dijamant",
    sr: "Diamond Push-Up", en: "Diamond Push-Up",
    icon: "💎", category: "push", difficulty: 3,
    xpWeight: 1.5,
    desc_sr: "Ruke formiraju dijamant. Maksimalna aktivacija tricepsa.",
    desc_en: "Hands form a diamond shape. Maximum tricep isolation.",
    muscles: { primary: ["tricep_long","tricep_lateral","tricep_medial"], secondary: ["pec_major_lower","delt_anterior"] },
  },
  {
    id: "sklekovi_decline",
    sr: "Sklekovi noge gore", en: "Decline Push-Up",
    icon: "📐", category: "push", difficulty: 4,
    xpWeight: 2.0,
    desc_sr: "Noge podignute, naglasak na gornjem delu grudiju i prednjim deltoidima.",
    desc_en: "Feet elevated, upper chest and anterior delt emphasis.",
    muscles: { primary: ["pec_major_upper","delt_anterior"], secondary: ["tricep_long","serratus"] },
  },
  {
    id: "explosive_pushup",
    sr: "Eksplozivni sklekovi", en: "Explosive Push-Up",
    icon: "💥", category: "push", difficulty: 5,
    xpWeight: 4.0,
    desc_sr: "Maksimalna eksplozivnost — ruke odvajaju od poda u vrhu pokreta.",
    desc_en: "Maximum explosiveness — hands leave the floor at the top.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","delt_anterior"] },
  },
  {
    id: "sklekovi_archer",
    sr: "Archer Push-Up", en: "Archer Push-Up",
    icon: "🏹", category: "push", difficulty: 6,
    xpWeight: 3.0,
    desc_sr: "Jedna ruka savija, druga ostaje ispružena. Prelaz ka jednoručnom skleku.",
    desc_en: "One arm bends while the other stays extended. Transition to one-arm push-up.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","delt_anterior","brachialis"] },
  },
  {
    id: "sklekovi_pike",
    sr: "Pike Push-Up", en: "Pike Push-Up",
    icon: "🔺", category: "push", difficulty: 6,
    xpWeight: 3.0,
    desc_sr: "Kuk gore, krećeš se prema podu. Priprema za handstand push-up.",
    desc_en: "Hips up, lower toward the floor. Handstand push-up preparation.",
    muscles: { primary: ["delt_anterior","delt_lateral"], secondary: ["tricep_long","trap_upper","pec_minor"] },
  },
  {
    id: "sklekovi_incline",
    sr: "Sklekovi ruke gore", en: "Incline Push-Up",
    icon: "↗️", category: "push", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Ruke na povišenoj površini. Lakša varijacija za početnike.",
    desc_en: "Hands on elevated surface. Easier variation for beginners.",
    muscles: { primary: ["pec_major_lower"], secondary: ["tricep_lateral","delt_anterior"] },
  },
  {
    id: "pseudo_planche_pushup",
    sr: "Pseudo Planche Push-Up", en: "Pseudo Planche Push-Up",
    icon: "⚡", category: "push", difficulty: 8,
    xpWeight: 5.0,
    desc_sr: "Ruke okrenute unazad, telo nagnuto napred. Direktna priprema za planche.",
    desc_en: "Hands rotated back, body leaned forward. Direct planche preparation.",
    muscles: { primary: ["delt_anterior","pec_minor","serratus"], secondary: ["tricep_long","pec_major_lower"] },
  },
  {
    id: "handstand_pushups",
    sr: "Handstand Push-Up", en: "Handstand Push-Up",
    icon: "🤸", category: "push", difficulty: 9,
    xpWeight: 10.0,
    desc_sr: "Sklekovi u handstand poziciji. Elitna vežba za ramena.",
    desc_en: "Push-ups in handstand position. Elite shoulder exercise.",
    muscles: { primary: ["delt_anterior","delt_lateral","trap_upper"], secondary: ["tricep_long","pec_minor","serratus"] },
  },
  {
    id: "sklekovi_jednorucan",
    sr: "Jednoručni sklek", en: "One Arm Push-Up",
    icon: "☝️", category: "push", difficulty: 9,
    xpWeight: 12.0,
    desc_sr: "Jedna ruka iza leđa. Vrhunska unilateralna vežba.",
    desc_en: "One hand behind back. Elite unilateral exercise.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","oblique_ext","delt_anterior"] },
  },

  // ══════════════════════════════════════════════════════════
  // PULL
  // ══════════════════════════════════════════════════════════
  {
    id: "australijski_zgibovi",
    sr: "Australijski zgibovi", en: "Australian Pull-Up",
    icon: "🦘", category: "pull", difficulty: 2,
    xpWeight: 1.0,
    desc_sr: "Horizontalni zgib. Noge na podu, telo pod uglom.",
    desc_en: "Horizontal pull. Feet on floor, body at angle.",
    muscles: { primary: ["lats","rhomboids","trap_mid"], secondary: ["bicep_long","bicep_short","brachialis","teres_major"] },
  },
  {
    id: "scapular_pulls",
    sr: "Scapular Pull", en: "Scapular Pull",
    icon: "🔧", category: "pull", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Aktivacija lopatice na šipki bez savijanja laktova. Osnova za zgibove.",
    desc_en: "Scapular retraction on the bar without elbow bend. Foundation for pull-ups.",
    muscles: { primary: ["trap_lower","rhomboids","serratus"], secondary: ["lats","teres_minor","infraspinatus"] },
  },
  {
    id: "chin_ups",
    sr: "Chin-Up (pothhvat)", en: "Chin-Up",
    icon: "💪", category: "pull", difficulty: 4,
    xpWeight: 3.0,
    desc_sr: "Pothhvat, dlanovi okrenuti ka tebi. Jači naglasak na bicepse.",
    desc_en: "Underhand grip, palms facing you. Greater bicep activation.",
    muscles: { primary: ["bicep_long","bicep_short","lats"], secondary: ["brachialis","rhomboids","trap_mid"] },
  },
  {
    id: "zgibovi_uski",
    sr: "Zgibovi uski", en: "Pull-Up",
    icon: "⬆️", category: "pull", difficulty: 4,
    xpWeight: 4.0,
    desc_sr: "Zahvat na širini ramena, prihvat. Osnovna vežba za leđa.",
    desc_en: "Shoulder-width overhand grip. Foundational back exercise.",
    muscles: { primary: ["lats","teres_major"], secondary: ["bicep_long","rhomboids","trap_mid","brachialis"] },
  },
  {
    id: "neutral_grip_pullups",
    sr: "Neutral zgibovi", en: "Neutral Grip Pull-Up",
    icon: "🤝", category: "pull", difficulty: 4,
    xpWeight: 4.0,
    desc_sr: "Paralelni hvatovi. Neutralan položaj za zglob.",
    desc_en: "Parallel handles. Neutral wrist position.",
    muscles: { primary: ["lats","brachialis"], secondary: ["bicep_long","teres_major","rhomboids"] },
  },
  {
    id: "zgibovi_siroki",
    sr: "Zgibovi široki", en: "Wide Pull-Up",
    icon: "🦅", category: "pull", difficulty: 5,
    xpWeight: 5.0,
    desc_sr: "Hvatanje šire od ramena. Maksimalni stretch latova.",
    desc_en: "Grip wider than shoulders. Maximum lat stretch.",
    muscles: { primary: ["lats","teres_major"], secondary: ["trap_mid","rhomboids","teres_minor","infraspinatus"] },
  },
  {
    id: "archer_pullup",
    sr: "Archer Pull-Up", en: "Archer Pull-Up",
    icon: "🏹", category: "pull", difficulty: 7,
    xpWeight: 7.0,
    desc_sr: "Jedna ruka vodi, druga pomaže. Prelaz ka jednoručnom zgibu.",
    desc_en: "One arm leads, other assists. Transition to one-arm pull-up.",
    muscles: { primary: ["lats","bicep_long"], secondary: ["teres_major","rhomboids","brachialis"] },
  },
  {
    id: "chest_to_bar",
    sr: "Chest-to-Bar Pull-Up", en: "Chest-to-Bar Pull-Up",
    icon: "🎯", category: "pull", difficulty: 7,
    xpWeight: 8.0,
    desc_sr: "Povlačenje sve dok grudi ne dodirnu šipku. Pun raspon pokreta.",
    desc_en: "Pull until chest touches the bar. Full range of motion.",
    muscles: { primary: ["lats","teres_major","rhomboids"], secondary: ["bicep_long","trap_lower","trap_mid"] },
  },
  {
    id: "explosive_pullup",
    sr: "Eksplozivni zgib", en: "Explosive Pull-Up",
    icon: "🚀", category: "pull", difficulty: 8,
    xpWeight: 10.0,
    desc_sr: "Maksimalna eksplozivnost — ruke napuštaju šipku na vrhu.",
    desc_en: "Maximum explosiveness — hands leave the bar at the top.",
    muscles: { primary: ["lats","teres_major"], secondary: ["bicep_long","trap_lower","delt_posterior"] },
  },
  {
    id: "lsit_pullup",
    sr: "L-Sit Pull-Up", en: "L-Sit Pull-Up",
    icon: "🔡", category: "pull", difficulty: 8,
    xpWeight: 12.0,
    desc_sr: "Zgib sa nogama u L poziciji. Kombinuje pull snagu i core stabilnost.",
    desc_en: "Pull-up with legs in L position. Combines pull strength and core stability.",
    muscles: { primary: ["lats","rectus_abdominis","iliopsoas"], secondary: ["bicep_long","teres_major","rectus_femoris"] },
  },
  {
    id: "muscle_up",
    sr: "Muscle-Up", en: "Muscle-Up",
    icon: "🌟", category: "pull", difficulty: 9,
    xpWeight: 15.0,
    desc_sr: "Zgib + propadanje u jednom eksplozivnom pokretu. Skill vežba.",
    desc_en: "Pull-up + dip in one explosive movement. Skill exercise.",
    muscles: { primary: ["lats","teres_major","tricep_long","delt_anterior"], secondary: ["bicep_long","pec_major_lower","rhomboids"] },
  },
  {
    id: "one_arm_pullup",
    sr: "Jednoručni zgib", en: "One Arm Pull-Up",
    icon: "☝️", category: "pull", difficulty: 10,
    xpWeight: 30.0,
    desc_sr: "Vrh calistenic pull snage. Jedna od najtežih vežbi uopšte.",
    desc_en: "The pinnacle of calisthenics pulling strength. One of the hardest exercises.",
    muscles: { primary: ["lats","bicep_long","teres_major"], secondary: ["brachialis","rhomboids","oblique_ext"] },
  },

  // ══════════════════════════════════════════════════════════
  // DIPS
  // ══════════════════════════════════════════════════════════
  {
    id: "propadanja_stolica",
    sr: "Propadanja na stolici", en: "Bench Dip",
    icon: "🪑", category: "dips", difficulty: 2,
    xpWeight: 1.0,
    desc_sr: "Ruke na klupi iza tebe, noge ispružene. Osnova za propadanja.",
    desc_en: "Hands on bench behind you, legs extended. Foundation for dips.",
    muscles: { primary: ["tricep_long","tricep_lateral"], secondary: ["delt_anterior","pec_major_lower"] },
  },
  {
    id: "propadanja",
    sr: "Propadanja", en: "Parallel Bar Dip",
    icon: "⬇️", category: "dips", difficulty: 5,
    xpWeight: 5.0,
    desc_sr: "Između paralelnih šipki. Osnova calistenic push snage.",
    desc_en: "Between parallel bars. Foundation of calisthenics push strength.",
    muscles: { primary: ["tricep_long","pec_major_lower","delt_anterior"], secondary: ["tricep_lateral","pec_minor","serratus"] },
  },
  {
    id: "straight_bar_dip",
    sr: "Straight Bar Dip", en: "Straight Bar Dip",
    icon: "🏋️", category: "dips", difficulty: 5,
    xpWeight: 4.0,
    desc_sr: "Propadanja na ravnoj šipki. Zahteva više balance i stabilnosti.",
    desc_en: "Dips on a straight bar. Requires more balance and stability.",
    muscles: { primary: ["tricep_long","pec_major_lower"], secondary: ["delt_anterior","serratus","pec_minor"] },
  },
  {
    id: "korean_dips",
    sr: "Korean Dip", en: "Korean Dip",
    icon: "🔱", category: "dips", difficulty: 7,
    xpWeight: 8.0,
    desc_sr: "Hvatanje iza leđa, telo seda dole. Izuzetno zahtevno za ramena.",
    desc_en: "Grip behind the back, body lowers down. Extremely demanding for shoulders.",
    muscles: { primary: ["delt_posterior","teres_minor","infraspinatus"], secondary: ["tricep_long","rhomboids"] },
  },
  {
    id: "russian_dip",
    sr: "Russian Dip", en: "Russian Dip",
    icon: "🇷🇺", category: "dips", difficulty: 8,
    xpWeight: 10.0,
    desc_sr: "Spuštanje na podlaktice na šipkama. Priprema za muscle-up.",
    desc_en: "Lowering to forearms on the bars. Muscle-up preparation.",
    muscles: { primary: ["tricep_long","pec_major_lower","delt_anterior"], secondary: ["serratus","pec_minor","trap_lower"] },
  },

  // ══════════════════════════════════════════════════════════
  // LEGS
  // ══════════════════════════════════════════════════════════
  {
    id: "cucnjevi",
    sr: "Čučnjevi", en: "Bodyweight Squat",
    icon: "🦵", category: "legs", difficulty: 1,
    xpWeight: 1.0,
    desc_sr: "Osnova snage donjih ekstremiteta. Puna amplituda pokreta.",
    desc_en: "Foundation of lower body strength. Full range of motion.",
    muscles: { primary: ["rectus_femoris","vastus_lat","vastus_med","vastus_int"], secondary: ["glute_max","glute_med","erector_spinae"] },
  },
  {
    id: "glute_bridge",
    sr: "Glute Bridge", en: "Glute Bridge",
    icon: "🌉", category: "legs", difficulty: 1,
    xpWeight: 1.0,
    desc_sr: "Podizanje kukova sa poda. Izolacija gluteusa.",
    desc_en: "Hip thrust from the floor. Glute isolation.",
    muscles: { primary: ["glute_max","glute_med"], secondary: ["bicep_femoris","semitendinosus","erector_spinae"] },
  },
  {
    id: "lunges",
    sr: "Iskoraci", en: "Lunge",
    icon: "🚶", category: "legs", difficulty: 2,
    xpWeight: 1.5,
    desc_sr: "Korak napred sa spuštanjem kolena. Unilateralna vežba.",
    desc_en: "Step forward and lower the knee. Unilateral exercise.",
    muscles: { primary: ["rectus_femoris","glute_max"], secondary: ["vastus_lat","vastus_med","bicep_femoris"] },
  },
  {
    id: "jump_squat",
    sr: "Skok čučanj", en: "Jump Squat",
    icon: "⬆️", category: "legs", difficulty: 3,
    xpWeight: 2.0,
    desc_sr: "Eksplozivni čučanj sa skokom. Razvija power i eksplozivnost.",
    desc_en: "Explosive squat with jump. Develops power and explosiveness.",
    muscles: { primary: ["rectus_femoris","glute_max","vastus_lat"], secondary: ["gastrocnemius","soleus","glute_med"] },
  },
  {
    id: "bulgarian_split",
    sr: "Bugarski split čučanj", en: "Bulgarian Split Squat",
    icon: "🎯", category: "legs", difficulty: 4,
    xpWeight: 3.0,
    desc_sr: "Zadnja noga na klupi, prednja radi posao. Intenzivna unilateralna vežba.",
    desc_en: "Rear foot elevated, front leg does the work. Intense unilateral exercise.",
    muscles: { primary: ["rectus_femoris","glute_max","glute_med"], secondary: ["vastus_lat","vastus_med","bicep_femoris"] },
  },
  {
    id: "calf_raises",
    sr: "Podizanje na prste", en: "Calf Raise",
    icon: "👣", category: "legs", difficulty: 1,
    xpWeight: 0.5,
    desc_sr: "Podizanje na prste. Izolacija listova.",
    desc_en: "Rising on toes. Calf isolation.",
    muscles: { primary: ["gastrocnemius","soleus"], secondary: [] },
  },
  {
    id: "sissy_squat",
    sr: "Sissy čučanj", en: "Sissy Squat",
    icon: "🔥", category: "legs", difficulty: 6,
    xpWeight: 5.0,
    desc_sr: "Kolena idu napred dok se telo naginje unazad. Ekstremna kvadriceps izolacija.",
    desc_en: "Knees travel forward as body leans back. Extreme quad isolation.",
    muscles: { primary: ["rectus_femoris","vastus_lat","vastus_med"], secondary: ["glute_max","gastrocnemius"] },
  },
  {
    id: "shrimp_squat",
    sr: "Shrimp čučanj", en: "Shrimp Squat",
    icon: "🦐", category: "legs", difficulty: 7,
    xpWeight: 7.0,
    desc_sr: "Jednonožni čučanj sa zadnjom nogom savijenom. Vrhunska kontrola i balans.",
    desc_en: "Single-leg squat with rear leg bent. Superior control and balance.",
    muscles: { primary: ["rectus_femoris","glute_max","vastus_lat"], secondary: ["vastus_med","bicep_femoris","glute_med"] },
  },
  {
    id: "pistol_squat",
    sr: "Pistol čučanj", en: "Pistol Squat",
    icon: "🔫", category: "legs", difficulty: 8,
    xpWeight: 8.0,
    desc_sr: "Jednonožni čučanj do dna sa drugom nogom ispruženom napred. Vrhunac.",
    desc_en: "Single-leg squat to depth with other leg extended forward. The pinnacle.",
    muscles: { primary: ["rectus_femoris","vastus_lat","vastus_med","glute_max"], secondary: ["bicep_femoris","glute_med","soleus"] },
  },
  {
    id: "nordic_curl",
    sr: "Nordic Curl", en: "Nordic Curl",
    icon: "🧊", category: "legs", difficulty: 9,
    xpWeight: 12.0,
    desc_sr: "Ekscentrično spuštanje sa fiksiranim stopalima. Jedna od najtežih hamstring vežbi.",
    desc_en: "Eccentric lowering with feet fixed. One of the hardest hamstring exercises.",
    muscles: { primary: ["bicep_femoris","semitendinosus","semimembranosus"], secondary: ["glute_max","gastrocnemius"] },
  },

  // ══════════════════════════════════════════════════════════
  // CORE (reps)
  // ══════════════════════════════════════════════════════════
  {
    id: "situps",
    sr: "Trbušnjaci", en: "Sit-Up",
    icon: "💪", category: "core", difficulty: 1,
    xpWeight: 1.0,
    desc_sr: "Klasični trbušnjaci. Podiži gornji deo tela sa poda.",
    desc_en: "Classic sit-ups. Raise the upper body off the floor.",
    muscles: { primary: ["rectus_abdominis"], secondary: ["oblique_ext","iliopsoas"] },
  },
  {
    id: "noge_u_vis",
    sr: "Podizanje nogu", en: "Leg Raise",
    icon: "🦵", category: "core", difficulty: 3,
    xpWeight: 2.0,
    desc_sr: "Podizanje ispruženih nogu sa poda. Donji trbuh.",
    desc_en: "Raising straight legs from the floor. Lower abs emphasis.",
    muscles: { primary: ["rectus_abdominis","iliopsoas"], secondary: ["rectus_femoris","transversus"] },
  },
  {
    id: "hanging_knee_raise",
    sr: "Podizanje kolena u visu", en: "Hanging Knee Raise",
    icon: "🔝", category: "core", difficulty: 3,
    xpWeight: 3.0,
    desc_sr: "Privlačenje kolena ka grudima u visu na šipki.",
    desc_en: "Drawing knees to chest while hanging from a bar.",
    muscles: { primary: ["rectus_abdominis","iliopsoas"], secondary: ["oblique_ext","transversus","lats"] },
  },
  {
    id: "hollow_body",
    sr: "Hollow Body Hold", en: "Hollow Body Hold",
    icon: "🌊", category: "core", difficulty: 3,
    xpWeight: 2.0,
    desc_sr: "Osnovna gimnastička pozicija. Ruke i noge podignuti sa poda, leđa sploštena.",
    desc_en: "Fundamental gymnastic position. Arms and legs lifted, lower back flat.",
    muscles: { primary: ["rectus_abdominis","transversus"], secondary: ["oblique_ext","iliopsoas"] },
  },
  {
    id: "hanging_leg_raise",
    sr: "Podizanje nogu u visu", en: "Hanging Leg Raise",
    icon: "⬆️", category: "core", difficulty: 5,
    xpWeight: 5.0,
    desc_sr: "Ispružene noge se podižu do horizontale u visu. Zahteva snagu i kontrolu.",
    desc_en: "Straight legs raised to horizontal while hanging. Requires strength and control.",
    muscles: { primary: ["rectus_abdominis","iliopsoas","rectus_femoris"], secondary: ["lats","oblique_ext","transversus"] },
  },
  {
    id: "ab_wheel",
    sr: "Ab Wheel", en: "Ab Wheel Rollout",
    icon: "⚙️", category: "core", difficulty: 6,
    xpWeight: 6.0,
    desc_sr: "Kotrljanje točkića napred sa ispruženim telom. Intenzivna vežba za ceo core.",
    desc_en: "Rolling the wheel forward with extended body. Intense full core exercise.",
    muscles: { primary: ["rectus_abdominis","transversus"], secondary: ["delt_anterior","serratus","oblique_ext","erector_spinae"] },
  },
  {
    id: "toes_to_bar",
    sr: "Nožni prsti do šipke", en: "Toes to Bar",
    icon: "🎯", category: "core", difficulty: 7,
    xpWeight: 8.0,
    desc_sr: "Podizanje nogu sve do šipke u visu. Pun raspon pokreta.",
    desc_en: "Raising legs all the way to the bar while hanging. Full range of motion.",
    muscles: { primary: ["rectus_abdominis","iliopsoas","lats"], secondary: ["oblique_ext","rectus_femoris","transversus"] },
  },
  {
    id: "windshield_wipers",
    sr: "Brisači za vetrobransko staklo", en: "Windshield Wipers",
    icon: "🌀", category: "core", difficulty: 8,
    xpWeight: 12.0,
    desc_sr: "Noge u horizontali u visu, rotiraju s leve na desnu stranu.",
    desc_en: "Legs at horizontal while hanging, rotating side to side.",
    muscles: { primary: ["oblique_ext","oblique_int","rectus_abdominis"], secondary: ["lats","iliopsoas","transversus"] },
  },
  {
    id: "dragon_flag",
    sr: "Dragon Flag", en: "Dragon Flag",
    icon: "🐲", category: "core", difficulty: 9,
    xpWeight: 15.0,
    desc_sr: "Celo telo u ravnoj liniji, oslonac samo na gornji deo leđa. Legendarni Bruce Lee pokret.",
    desc_en: "Whole body in a straight line, support only on upper back. Bruce Lee's legendary move.",
    muscles: { primary: ["rectus_abdominis","transversus","erector_spinae"], secondary: ["glute_max","iliopsoas","serratus","oblique_ext"] },
  },

  // ══════════════════════════════════════════════════════════
  // STATIC HOLDS (isHold: true, XP per second)
  // ══════════════════════════════════════════════════════════
  {
    id: "plank",
    sr: "Plank", en: "Plank",
    icon: "📏", category: "hold", difficulty: 2,
    isHold: true, xpWeight: 0.3,
    desc_sr: "Osnovna izometricna vežba. Telo u ravnoj liniji, oslonac na laktovima.",
    desc_en: "Foundational isometric exercise. Body straight, supported on forearms.",
    muscles: { primary: ["transversus","rectus_abdominis"], secondary: ["delt_anterior","glute_max","serratus"] },
  },
  {
    id: "side_plank",
    sr: "Bočni plank", en: "Side Plank",
    icon: "📐", category: "hold", difficulty: 3,
    isHold: true, xpWeight: 0.4,
    desc_sr: "Bočna varijanta planka. Fokus na bočnim mišićima trbuha.",
    desc_en: "Side variant of plank. Focus on lateral core muscles.",
    muscles: { primary: ["oblique_ext","oblique_int","transversus"], secondary: ["glute_med","delt_lateral"] },
  },
  {
    id: "dead_hang",
    sr: "Dead Hang", en: "Dead Hang",
    icon: "⚓", category: "hold", difficulty: 2,
    isHold: true, xpWeight: 0.5,
    desc_sr: "Pasivni vis na šipki. Razvija grip snagu i dekomprimuje kičmu.",
    desc_en: "Passive hang from bar. Builds grip strength and decompresses spine.",
    muscles: { primary: ["lats","trap_lower","brachioradialis"], secondary: ["serratus","teres_minor","infraspinatus"] },
  },
  {
    id: "one_arm_hang",
    sr: "Jednoručni hang", en: "One Arm Hang",
    icon: "☝️", category: "hold", difficulty: 6,
    isHold: true, xpWeight: 1.5,
    desc_sr: "Jednoručni pasivni vis. Izuzetna grip snaga i stabilnost ramena.",
    desc_en: "One-arm passive hang. Exceptional grip strength and shoulder stability.",
    muscles: { primary: ["lats","brachioradialis","trap_lower"], secondary: ["teres_minor","infraspinatus","serratus"] },
  },
  {
    id: "l_sit",
    sr: "L-Sit", en: "L-Sit",
    icon: "📐", category: "hold", difficulty: 6,
    isHold: true, xpWeight: 1.0,
    desc_sr: "Noge ispružene horizontalno u visu ili osloncu. Kombinuje core i pull snagu.",
    desc_en: "Legs extended horizontally in hang or support. Combines core and pull strength.",
    muscles: { primary: ["rectus_abdominis","iliopsoas","rectus_femoris"], secondary: ["transversus","lats","tricep_long"] },
  },
  {
    id: "tuck_front_lever",
    sr: "Tuck Front Lever", en: "Tuck Front Lever",
    icon: "🔤", category: "hold", difficulty: 7,
    isHold: true, xpWeight: 1.5,
    desc_sr: "Kolena privučena, telo horizontalno. Priprema za full front lever.",
    desc_en: "Knees tucked, body horizontal. Preparation for full front lever.",
    muscles: { primary: ["lats","teres_major","rectus_abdominis"], secondary: ["rhomboids","trap_lower","bicep_long"] },
  },
  {
    id: "wall_handstand",
    sr: "Handstand uz zid", en: "Wall Handstand Hold",
    icon: "🧱", category: "hold", difficulty: 5,
    isHold: true, xpWeight: 1.5,
    desc_sr: "Handstand sa leđima ili grudima ka zidu. Razvija snagu ramena i balans.",
    desc_en: "Handstand with back or chest to wall. Builds shoulder strength and balance.",
    muscles: { primary: ["delt_anterior","delt_lateral","trap_upper"], secondary: ["serratus","pec_minor","tricep_long"] },
  },
  {
    id: "freestanding_handstand",
    sr: "Freestanding Handstand", en: "Freestanding Handstand",
    icon: "⭐", category: "hold", difficulty: 8,
    isHold: true, xpWeight: 2.5,
    desc_sr: "Handstand bez oslonca. Zahteva mesece treninga balansa i snage.",
    desc_en: "Handstand without support. Requires months of balance and strength training.",
    muscles: { primary: ["delt_anterior","delt_lateral","serratus"], secondary: ["trap_upper","pec_minor","tricep_long","transversus"] },
  },
  {
    id: "back_lever",
    sr: "Back Lever", en: "Back Lever",
    icon: "⬇️", category: "hold", difficulty: 8,
    isHold: true, xpWeight: 3.0,
    desc_sr: "Telo horizontalno ispod šipke, licem nadole. Elitna skill vežba.",
    desc_en: "Body horizontal below the bar, face down. Elite skill exercise.",
    muscles: { primary: ["pec_major_lower","delt_anterior","teres_major"], secondary: ["lats","bicep_long","serratus","erector_spinae"] },
  },
  {
    id: "front_lever",
    sr: "Front Lever", en: "Front Lever",
    icon: "⬆️", category: "hold", difficulty: 9,
    isHold: true, xpWeight: 3.0,
    desc_sr: "Telo horizontalno ispod šipke, licem gore. Jedna od najtežih skill vežbi.",
    desc_en: "Body horizontal below the bar, face up. One of the hardest skill exercises.",
    muscles: { primary: ["lats","teres_major","rectus_abdominis"], secondary: ["rhomboids","trap_lower","bicep_long","iliopsoas"] },
  },
  {
    id: "human_flag",
    sr: "Human Flag", en: "Human Flag",
    icon: "🚩", category: "hold", difficulty: 10,
    isHold: true, xpWeight: 4.0,
    desc_sr: "Horizontalni vis na vertikalnoj šipki. Simbolički pokret street workoutera.",
    desc_en: "Horizontal hold on a vertical pole. Iconic street workout movement.",
    muscles: { primary: ["oblique_ext","oblique_int","lats","delt_lateral"], secondary: ["trap_lower","serratus","glute_med"] },
  },
  {
    id: "tuck_planche",
    sr: "Tuck Planche", en: "Tuck Planche",
    icon: "✈️", category: "hold", difficulty: 8,
    isHold: true, xpWeight: 3.5,
    desc_sr: "Kolena privučena, telo paralelno sa tlom. Priprema za full planche.",
    desc_en: "Knees tucked, body parallel to ground. Preparation for full planche.",
    muscles: { primary: ["delt_anterior","serratus","pec_minor"], secondary: ["tricep_long","rectus_abdominis","transversus"] },
  },
  {
    id: "straddle_planche",
    sr: "Straddle Planche", en: "Straddle Planche",
    icon: "🛸", category: "hold", difficulty: 10,
    isHold: true, xpWeight: 5.0,
    desc_sr: "Noge raširene, telo horizontalno. Korak pre full planche.",
    desc_en: "Legs straddled, body horizontal. Step before full planche.",
    muscles: { primary: ["delt_anterior","serratus","pec_minor","tricep_long"], secondary: ["rectus_abdominis","transversus","glute_med"] },
  },
  {
    id: "full_planche",
    sr: "Full Planche", en: "Full Planche",
    icon: "🌌", category: "hold", difficulty: 10,
    isHold: true, xpWeight: 8.0,
    desc_sr: "Noge zajedno, telo horizontalno. Vrh calistenic skill snage.",
    desc_en: "Legs together, body horizontal. The apex of calisthenics skill strength.",
    muscles: { primary: ["delt_anterior","serratus","pec_minor","tricep_long"], secondary: ["rectus_abdominis","transversus","glute_max"] },
  },
  {
    id: "victorian_hold",
    sr: "Victorian Hold", en: "Victorian Hold",
    icon: "👑", category: "hold", difficulty: 10,
    isHold: true, xpWeight: 12.0,
    desc_sr: "Telo horizontalno iznad šipki, licem gore — bez oslonca na laktove. Prestiž.",
    desc_en: "Body horizontal above bars, face up — no elbow support. Pure prestige.",
    muscles: { primary: ["delt_posterior","teres_minor","infraspinatus"], secondary: ["tricep_long","lats","rhomboids"] },
  },

  // ══════════════════════════════════════════════════════════
  // SKILL / MISC
  // ══════════════════════════════════════════════════════════
  {
    id: "skin_the_cat",
    sr: "Skin the Cat", en: "Skin the Cat",
    icon: "🌀", category: "skill", difficulty: 6,
    xpWeight: 6.0,
    desc_sr: "Rotacija tela kroz šipku u visu. Mobilnost ramena i kontrola.",
    desc_en: "Body rotation through the bar while hanging. Shoulder mobility and control.",
    muscles: { primary: ["lats","teres_major","serratus"], secondary: ["pec_minor","teres_minor","rectus_abdominis"] },
  },
  {
    id: "back_lever_swing",
    sr: "Back Lever Swing", en: "Back Lever Swing",
    icon: "🔄", category: "skill", difficulty: 5,
    xpWeight: 4.0,
    desc_sr: "Dinamičan ulazak u back lever poziciju kroz zamah.",
    desc_en: "Dynamic entry into back lever position through a swing.",
    muscles: { primary: ["lats","teres_major","pec_major_lower"], secondary: ["delt_anterior","erector_spinae"] },
  },
  {
    id: "burpees",
    sr: "Burpees", en: "Burpees",
    icon: "💥", category: "skill", difficulty: 4,
    xpWeight: 2.5,
    desc_sr: "Kompleksna vežba: sklekovi + skok. Kondicioniranje celog tela.",
    desc_en: "Complex exercise: push-up + jump. Full body conditioning.",
    muscles: { primary: ["pec_major_lower","rectus_femoris","glute_max"], secondary: ["tricep_long","delt_anterior","gastrocnemius","rectus_abdominis"] },
  },
  {
    id: "mountain_climbers",
    sr: "Mountain Climbers", en: "Mountain Climbers",
    icon: "🧗", category: "skill", difficulty: 3,
    xpWeight: 1.5,
    desc_sr: "Naizmenično privlačenje kolena u položaju skleka. Kardio + core.",
    desc_en: "Alternately drawing knees to chest in push-up position. Cardio + core.",
    muscles: { primary: ["rectus_abdominis","iliopsoas","rectus_femoris"], secondary: ["delt_anterior","transversus","pec_major_lower"] },
  },
// ══════════════════════════════════════════════════════════
// PUSH - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "incline_pushup",
    sr: "Incline Sklekovi", en: "Incline Push-Up",
    icon: "↗️", category: "push", difficulty: 1,
    xpWeight: 0.8,
    desc_sr: "Ruke na povišenoj podlozi, telo pod uglom. Lakša varijanta, odlično za početnike.",
    desc_en: "Hands on an elevated surface. Easier variation, great for building base strength.",
    muscles: { primary: ["pec_major_lower","pec_minor"], secondary: ["tricep_lateral","delt_anterior"] },
  },
  {
    id: "decline_pushup",
    sr: "Decline Sklekovi", en: "Decline Push-Up",
    icon: "📐", category: "push", difficulty: 3,
    xpWeight: 1.4,
    desc_sr: "Noge na povišenoj podlozi, naglasak na gornjim grudima i ramenima.",
    desc_en: "Feet elevated, emphasis on upper chest and anterior deltoids.",
    muscles: { primary: ["pec_major_upper","delt_anterior"], secondary: ["tricep_long","serratus"] },
  },
  {
    id: "hindu_pushup",
    sr: "Hindu Sklek", en: "Hindu Push-Up",
    icon: "🌊", category: "push", difficulty: 3,
    xpWeight: 1.3,
    desc_sr: "Dinamični pokret u obliku luka — kombinacija kretanja kukova, ramena i grudi.",
    desc_en: "Dynamic arcing movement combining hip drive, shoulder and chest engagement.",
    muscles: { primary: ["pec_major_upper","delt_anterior"], secondary: ["tricep_long","erector_spinae","serratus"] },
  },
  {
    id: "divebomber_pushup",
    sr: "Dive Bomber Sklek", en: "Dive Bomber Push-Up",
    icon: "🚀", category: "push", difficulty: 4,
    xpWeight: 1.5,
    desc_sr: "Složeni pokret: spuštanje poput aviona, klizanje napred i podizanje. Full-body push vežba.",
    desc_en: "Complex sweeping movement: dive forward and sweep through like a plane. Full-body push.",
    muscles: { primary: ["pec_major_upper","delt_anterior","tricep_long"], secondary: ["erector_spinae","serratus","tricep_lateral"] },
  },
  {
    id: "spiderman_pushup",
    sr: "Spiderman Sklek", en: "Spiderman Push-Up",
    icon: "🕷️", category: "push", difficulty: 4,
    xpWeight: 1.5,
    desc_sr: "Pri spuštanju, koleno se privlači prema laktu. Kombinacija push-a i core rotacije.",
    desc_en: "Bring knee to elbow as you lower. Combines push strength with core rotation.",
    muscles: { primary: ["pec_major_lower","tricep_lateral"], secondary: ["oblique_ext","rectus_abdominis","delt_anterior"] },
  },
  {
    id: "typewriter_pushup",
    sr: "Pisaća Mašina Sklek", en: "Typewriter Push-Up",
    icon: "⌨️", category: "push", difficulty: 6,
    xpWeight: 2.0,
    desc_sr: "Na dnu pokreta, telo se pomera bočno — levo-desno poput pisaće mašine. Odlično za grudi.",
    desc_en: "At the bottom, shift bodyweight side to side like a typewriter. Excellent chest builder.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","delt_anterior","serratus"] },
  },
  {
    id: "ring_pushup",
    sr: "Sklek na karikama", en: "Ring Push-Up",
    icon: "⭕", category: "push", difficulty: 4,
    xpWeight: 1.8,
    desc_sr: "Sklekovi na gimnastičkim karikama. Nestabilnost aktivira stabilizatore i serratus.",
    desc_en: "Push-ups on gymnastics rings. Instability activates stabilizers and serratus.",
    muscles: { primary: ["pec_major_lower","pec_major_upper"], secondary: ["tricep_lateral","delt_anterior","serratus","brachialis"] },
  },
  {
    id: "ring_archer_pushup",
    sr: "Ring Archer Sklek", en: "Ring Archer Push-Up",
    icon: "🏹", category: "push", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Archer push-up na karikama — asimetričan pritisak uz nestabilnost karika.",
    desc_en: "Archer push-up on rings — asymmetric load combined with ring instability.",
    muscles: { primary: ["pec_major_upper","pec_major_lower"], secondary: ["tricep_long","delt_anterior","serratus"] },
  },
  {
    id: "planche_lean",
    sr: "Planche Lean", en: "Planche Lean",
    icon: "📏", category: "push", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "U položaju skleka, nagnuti telo napred pomeranjem težišta ka prstima. Priprema za planche.",
    desc_en: "In push-up position, lean forward shifting weight toward fingers. Planche prep drill.",
    muscles: { primary: ["delt_anterior","pec_minor"], secondary: ["tricep_long","serratus","transversus"] },
  },
  {
    id: "maltese_lean",
    sr: "Maltese Lean", en: "Maltese Lean",
    icon: "✈️", category: "push", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Ekstremni planche lean sa rukama široko — priprema za Maltese poziciju.",
    desc_en: "Extreme planche lean with wide arm position — preparation for the Maltese.",
    muscles: { primary: ["delt_anterior","pec_major_lower"], secondary: ["tricep_long","serratus","pec_minor"] },
  },
  {
    id: "deep_pushup",
    sr: "Duboki Sklek", en: "Deep Push-Up",
    icon: "⬇️", category: "push", difficulty: 3,
    xpWeight: 1.4,
    desc_sr: "Sklekovi na podlogama/knjigama koje podižu ruke — povećan opseg pokreta za grudi.",
    desc_en: "Push-ups with handles or books elevating hands — increased range of motion for chest.",
    muscles: { primary: ["pec_major_lower","pec_major_upper"], secondary: ["tricep_long","delt_anterior","serratus"] },
  },
  {
    id: "tiger_bend_pushup",
    sr: "Tiger Bend Push-Up", en: "Tiger Bend Push-Up",
    icon: "🐯", category: "push", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Spuštanje na podlaktice iz handstand pozicije i vraćanje na ruke. Izuzetno zahtevno za ramena.",
    desc_en: "From handstand, lower to forearms and press back up. Extremely demanding shoulder movement.",
    muscles: { primary: ["delt_anterior","tricep_long"], secondary: ["pec_major_upper","trap_lower","serratus"] },
  },
  {
    id: "ninety_degree_pushup",
    sr: "90° Push-Up", en: "90 Degree Push-Up",
    icon: "📐", category: "push", difficulty: 9,
    xpWeight: 3.5,
    desc_sr: "U pike položaju, savijanje laktova do 90° i zadržavanje. Jedna od najtežih push varijanti.",
    desc_en: "In pike position, bend elbows to 90° and hold. One of the hardest push variants.",
    muscles: { primary: ["delt_anterior","tricep_long"], secondary: ["pec_major_upper","trap_lower","serratus"] },
  },

// ══════════════════════════════════════════════════════════
// PULL - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "commando_pullup",
    sr: "Komando Zgib", en: "Commando Pull-Up",
    icon: "⚔️", category: "pull", difficulty: 5,
    xpWeight: 2.0,
    desc_sr: "Zgib paralelnim hvat, naizmenično se levo-desno sklanjati oko šipke. Odlično za biceps.",
    desc_en: "Neutral grip pull-up alternating sides of the bar. Great for biceps and lat activation.",
    muscles: { primary: ["lats","bicep_long","bicep_short"], secondary: ["teres_major","brachialis","brachioradialis"] },
  },
  {
    id: "typewriter_pullup",
    sr: "Pisaća Mašina Zgib", en: "Typewriter Pull-Up",
    icon: "⌨️", category: "pull", difficulty: 7,
    xpWeight: 2.8,
    desc_sr: "Na vrhu zgiba, prebaciti težinu sa jedne strane na drugu horizontalnim pokretom.",
    desc_en: "At the top of the pull-up, shift weight from side to side horizontally.",
    muscles: { primary: ["lats","bicep_long"], secondary: ["teres_major","pec_major_upper","brachialis"] },
  },
  {
    id: "mixed_grip_pullup",
    sr: "Mixed Grip Zgib", en: "Mixed Grip Pull-Up",
    icon: "🤲", category: "pull", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "Jedna ruka pothvatom, druga nathvatom. Aktivira različite delove leđa i bicepsa.",
    desc_en: "One hand supinated, one pronated. Activates different parts of back and biceps.",
    muscles: { primary: ["lats","bicep_long","bicep_short"], secondary: ["teres_major","brachioradialis","brachialis"] },
  },
  {
    id: "around_the_world_pullup",
    sr: "Around The World Zgib", en: "Around The World Pull-Up",
    icon: "🌍", category: "pull", difficulty: 7,
    xpWeight: 2.8,
    desc_sr: "Kružni pokret bradе oko šipke — kombinuje pull strength i kontrolu ramena.",
    desc_en: "Circular movement of the chin around the bar — combines pull strength and shoulder control.",
    muscles: { primary: ["lats","bicep_long"], secondary: ["teres_major","pec_major_upper","trap_mid"] },
  },
  {
    id: "ice_cream_maker",
    sr: "Ice Cream Maker", en: "Ice Cream Maker",
    icon: "🍦", category: "pull", difficulty: 8,
    xpWeight: 3.2,
    desc_sr: "Iz dead hang-a, rotirati telo do front lever pozicije i nazad. Vrhunska vežba za cela leđa.",
    desc_en: "From dead hang, rotate body to front lever position and back. Elite full-back exercise.",
    muscles: { primary: ["lats","teres_major","rectus_abdominis"], secondary: ["bicep_long","oblique_ext","transversus"] },
  },
  {
    id: "front_lever_row",
    sr: "Front Lever Row", en: "Front Lever Row",
    icon: "⬆️", category: "pull", difficulty: 9,
    xpWeight: 3.5,
    desc_sr: "Iz front lever pozicije, povlačenje tela prema šipki. Ekstremno zahtevno za leđa i core.",
    desc_en: "From front lever position, pull body to the bar. Extremely demanding for back and core.",
    muscles: { primary: ["lats","teres_major","rhomboids"], secondary: ["bicep_long","rectus_abdominis","trap_lower"] },
  },
  {
    id: "tuck_front_lever_row",
    sr: "Tuck Front Lever Row", en: "Tuck Front Lever Row",
    icon: "⬆️", category: "pull", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Rowing iz tuck front lever pozicije. Priprema za puni front lever row.",
    desc_en: "Rowing from tuck front lever position. Preparation for full front lever row.",
    muscles: { primary: ["lats","teres_major"], secondary: ["bicep_long","rhomboids","trap_lower"] },
  },
  {
    id: "adv_tuck_front_lever_row",
    sr: "Advanced Tuck Front Lever Row", en: "Advanced Tuck Front Lever Row",
    icon: "⬆️", category: "pull", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Rowing iz napredne tuck front lever pozicije — kuk u ravni sa ramenima.",
    desc_en: "Rowing from advanced tuck front lever — hips level with shoulders.",
    muscles: { primary: ["lats","teres_major","rhomboids"], secondary: ["bicep_long","rectus_abdominis","trap_lower"] },
  },
  {
    id: "inverted_row",
    sr: "Inverted Row", en: "Inverted Row",
    icon: "🦅", category: "pull", difficulty: 3,
    xpWeight: 1.2,
    desc_sr: "Ležeći ispod šipke, povlačenje grudi prema šipki. Odlično za početnike i rehabilitaciju.",
    desc_en: "Lying under a bar, pull chest to bar. Great for beginners and rehabilitation.",
    muscles: { primary: ["lats","rhomboids","trap_mid"], secondary: ["bicep_short","teres_minor","infraspinatus"] },
  },
  {
    id: "ring_row",
    sr: "Ring Row", en: "Ring Row",
    icon: "⭕", category: "pull", difficulty: 3,
    xpWeight: 1.3,
    desc_sr: "Povlačenje tela prema karikama u horiozntalnom položaju. Može se otežati spuštanjem ugla.",
    desc_en: "Pull body toward rings horizontally. Can be progressed by lowering body angle.",
    muscles: { primary: ["lats","rhomboids","trap_mid"], secondary: ["bicep_short","teres_minor","infraspinatus"] },
  },
  {
    id: "archer_ring_row",
    sr: "Archer Ring Row", en: "Archer Ring Row",
    icon: "🏹", category: "pull", difficulty: 6,
    xpWeight: 2.2,
    desc_sr: "Asimetrični ring row — jedna ruka vuče, druga ostaje ispružena. Priprema za jednoručne vežbe.",
    desc_en: "Asymmetric ring row — one arm pulls, one stays extended. Preparation for one-arm work.",
    muscles: { primary: ["lats","rhomboids"], secondary: ["bicep_long","teres_major","trap_mid"] },
  },
  {
    id: "false_grip_pullup",
    sr: "False Grip Zgib", en: "False Grip Pull-Up",
    icon: "✊", category: "pull", difficulty: 6,
    xpWeight: 2.2,
    desc_sr: "Zgib sa false grip hvat-om (zglob prelazi šipku). Neophodan za muscle-up na karikama.",
    desc_en: "Pull-up with false grip (wrist over bar). Essential for ring muscle-up progression.",
    muscles: { primary: ["lats","bicep_long"], secondary: ["teres_major","brachialis","brachioradialis"] },
  },
  {
    id: "rope_climb",
    sr: "Penjanje po Konopcu", en: "Rope Climb",
    icon: "🪢", category: "pull", difficulty: 6,
    xpWeight: 2.5,
    desc_sr: "Penjanje uz konopac samo rukama ili uz pomoć nogu. Odlično za grip i leđa.",
    desc_en: "Climbing a rope with arms only or assisted by legs. Great for grip and back strength.",
    muscles: { primary: ["lats","bicep_long","brachialis"], secondary: ["teres_major","brachioradialis","forearm_flex"] },
  },
  {
    id: "towel_pullup",
    sr: "Towel Zgib", en: "Towel Pull-Up",
    icon: "🧣", category: "pull", difficulty: 6,
    xpWeight: 2.2,
    desc_sr: "Zgib sa peškirom prebaèenim preko šipke. Enormno opterećuje grip i podlaktice.",
    desc_en: "Pull-up using a towel draped over a bar. Enormously loads grip and forearms.",
    muscles: { primary: ["lats","bicep_long","brachioradialis"], secondary: ["teres_major","brachialis","trap_lower"] },
  },
  {
    id: "explosive_chest_slap_pullup",
    sr: "Eksplozivni Zgib Udarac u Grudi", en: "Explosive Chest Slap Pull-Up",
    icon: "⚡", category: "pull", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Eksplozivni zgib toliko snažan da možeš tapšati u grudi pre dohvatanja šipke.",
    desc_en: "Explosive pull-up powerful enough to clap chest before catching the bar again.",
    muscles: { primary: ["lats","bicep_long","teres_major"], secondary: ["rhomboids","trap_lower","brachialis"] },
  },

// ══════════════════════════════════════════════════════════
// DIPS - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "bench_dip_elevated",
    sr: "Propadanja sa Nogama na Klupi", en: "Bench Dip Feet Elevated",
    icon: "🪑", category: "dips", difficulty: 3,
    xpWeight: 1.3,
    desc_sr: "Propadanja sa rukama i nogama na odvojenim klupama — težina celog tela na tricepsu.",
    desc_en: "Dips with hands on one bench, feet on another — full body weight on triceps.",
    muscles: { primary: ["tricep_long","tricep_lateral","tricep_medial"], secondary: ["delt_anterior","pec_major_lower"] },
  },
  {
    id: "ring_dip",
    sr: "Ring Dip", en: "Ring Dip",
    icon: "⭕", category: "dips", difficulty: 6,
    xpWeight: 2.5,
    desc_sr: "Propadanja na gimnastičkim karikama. Nestabilnost zahteva ogromnu kontrolu ramena i grudi.",
    desc_en: "Dips on gymnastics rings. Instability demands immense shoulder and chest control.",
    muscles: { primary: ["pec_major_lower","tricep_long","delt_anterior"], secondary: ["serratus","pec_minor","tricep_lateral"] },
  },
  {
    id: "bulgarian_ring_dip",
    sr: "Bugarski Ring Dip", en: "Bulgarian Ring Dip",
    icon: "🇧🇬", category: "dips", difficulty: 7,
    xpWeight: 2.8,
    desc_sr: "Ring dip sa pokretom napred — brada ide ispred karika. Veći fokus na grudi.",
    desc_en: "Ring dip moving forward — chin travels in front of rings. Greater chest involvement.",
    muscles: { primary: ["pec_major_lower","pec_major_upper","tricep_long"], secondary: ["delt_anterior","serratus","pec_minor"] },
  },
  {
    id: "deep_ring_dip",
    sr: "Duboki Ring Dip", en: "Deep Ring Dip",
    icon: "⬇️", category: "dips", difficulty: 7,
    xpWeight: 2.8,
    desc_sr: "Ring dip sa maksimalnim opsegom pokreta — ramena ispod lakata. Zahteva veliku mobilnost.",
    desc_en: "Ring dip with maximum range of motion — shoulders below elbows. Requires great mobility.",
    muscles: { primary: ["pec_major_lower","tricep_long"], secondary: ["delt_anterior","pec_minor","serratus"] },
  },
  {
    id: "korean_ring_dip_elevated",
    sr: "Korean Ring Dip (Noge Podigute)", en: "Korean Ring Dip Feet Elevated",
    icon: "🔱", category: "dips", difficulty: 8,
    xpWeight: 3.2,
    desc_sr: "Korean dip na karikama sa podignutim nogama. Jedna od najtežih dip varijanti.",
    desc_en: "Korean dip on rings with feet elevated. One of the most demanding dip variations.",
    muscles: { primary: ["tricep_long","delt_anterior"], secondary: ["pec_major_lower","trap_lower","serratus"] },
  },

// ══════════════════════════════════════════════════════════
// LEGS - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "cossack_squat",
    sr: "Kozački Čučanj", en: "Cossack Squat",
    icon: "🥾", category: "legs", difficulty: 4,
    xpWeight: 1.6,
    desc_sr: "Bočni čučanj sa jednom nogom ispruženom u stranu. Odlično za mobilnost kuka i kvadricepse.",
    desc_en: "Lateral squat with one leg extended to the side. Great for hip mobility and quads.",
    muscles: { primary: ["vastus_med","vastus_lat","glute_med"], secondary: ["glute_max","bicep_femoris","semitendinosus"] },
  },
  {
    id: "step_up",
    sr: "Step Up", en: "Step Up",
    icon: "🪜", category: "legs", difficulty: 2,
    xpWeight: 1.0,
    desc_sr: "Koračanje na povišenu podlogu jednom nogom. Odlično za kvadricepse i ravnotežu.",
    desc_en: "Stepping onto an elevated surface one leg at a time. Great for quads and balance.",
    muscles: { primary: ["rectus_femoris","vastus_lat","glute_max"], secondary: ["vastus_med","glute_med","gastrocnemius"] },
  },
  {
    id: "box_jump",
    sr: "Box Jump", en: "Box Jump",
    icon: "📦", category: "legs", difficulty: 4,
    xpWeight: 1.8,
    desc_sr: "Eksplozivni skok na povišenu podlogu (kutiju). Razvija eksplozivnost i jačinu nogu.",
    desc_en: "Explosive jump onto an elevated box. Develops explosive power and leg strength.",
    muscles: { primary: ["glute_max","rectus_femoris","vastus_lat"], secondary: ["gastrocnemius","soleus","bicep_femoris"] },
  },
  {
    id: "broad_jump",
    sr: "Skok u Daljinu", en: "Broad Jump",
    icon: "↔️", category: "legs", difficulty: 4,
    xpWeight: 1.8,
    desc_sr: "Eksplozivni skok horizontalno što dalje moguće. Razvija horizontalnu eksplozivnost.",
    desc_en: "Explosive horizontal jump as far as possible. Develops horizontal explosive power.",
    muscles: { primary: ["glute_max","rectus_femoris"], secondary: ["gastrocnemius","bicep_femoris","soleus"] },
  },
  {
    id: "jumping_lunges",
    sr: "Jumping Iskoraci", en: "Jumping Lunges",
    icon: "🏃", category: "legs", difficulty: 4,
    xpWeight: 1.6,
    desc_sr: "Eksplozivni iskoraci sa skokom i promenom noge u vazduhu. Kardio i snaga nogu.",
    desc_en: "Explosive lunges with a jump, switching legs mid-air. Cardio and leg strength combo.",
    muscles: { primary: ["glute_max","rectus_femoris","vastus_lat"], secondary: ["gastrocnemius","bicep_femoris","iliopsoas"] },
  },
  {
    id: "curtsy_lunge",
    sr: "Curtsy Iskorak", en: "Curtsy Lunge",
    icon: "🎭", category: "legs", difficulty: 3,
    xpWeight: 1.2,
    desc_sr: "Iskorak unakrst — zadnja noga prelazi iza prednje. Naglasak na gluteuse i abduktore.",
    desc_en: "Cross-behind lunge — rear foot crosses behind front. Emphasis on glutes and abductors.",
    muscles: { primary: ["glute_max","glute_med","vastus_lat"], secondary: ["rectus_femoris","glute_min","iliopsoas"] },
  },
  {
    id: "single_leg_glute_bridge",
    sr: "Jednonožni Glute Bridge", en: "Single Leg Glute Bridge",
    icon: "🌉", category: "legs", difficulty: 3,
    xpWeight: 1.3,
    desc_sr: "Glute bridge na jednoj nozi. Povećava unilateralno opterećenje gluteusa.",
    desc_en: "Glute bridge performed on one leg. Increases unilateral glute loading.",
    muscles: { primary: ["glute_max","glute_med"], secondary: ["bicep_femoris","semitendinosus","transversus"] },
  },
  {
    id: "single_leg_calf_raise",
    sr: "Jednonožno Podizanje na Prste", en: "Single Leg Calf Raise",
    icon: "👣", category: "legs", difficulty: 3,
    xpWeight: 1.2,
    desc_sr: "Podizanje na prste jednom nogom, potencijalno na stepenici za veći opseg pokreta.",
    desc_en: "Calf raise on one leg, optionally on a step for greater range of motion.",
    muscles: { primary: ["gastrocnemius","soleus"], secondary: ["glute_med","tibialis_ant"] },
  },
  {
    id: "assisted_pistol_squat",
    sr: "Asistovani Pistol Čučanj", en: "Assisted Pistol Squat",
    icon: "🤝", category: "legs", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "Pistol čučanj uz oslonac za ruku. Priprema za puni pistol čučanj.",
    desc_en: "Pistol squat with hand support. Preparation for the full pistol squat.",
    muscles: { primary: ["rectus_femoris","vastus_med","vastus_lat"], secondary: ["glute_max","glute_med","soleus"] },
  },
  {
    id: "atg_split_squat",
    sr: "ATG Split Čučanj", en: "ATG Split Squat",
    icon: "🧎", category: "legs", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "Ass-to-grass split čučanj sa naglaskom na puno opružanje kolena napred i mobilnost skočnog.",
    desc_en: "Full range split squat with knee tracking far forward and ankle mobility emphasis.",
    muscles: { primary: ["vastus_med","rectus_femoris","glute_max"], secondary: ["vastus_lat","soleus","iliopsoas"] },
  },
  {
    id: "wall_sit",
    sr: "Wall Sit", en: "Wall Sit",
    icon: "🧱", category: "legs", difficulty: 2,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "Sedenje uz zid sa koljenima pod 90°. Izometrijska vežba za kvadricepse.",
    desc_en: "Sitting against a wall with knees at 90°. Isometric exercise for the quadriceps.",
    muscles: { primary: ["rectus_femoris","vastus_med","vastus_lat"], secondary: ["vastus_int","glute_max"] },
  },
  {
    id: "reverse_nordic_curl",
    sr: "Reverse Nordic Curl", en: "Reverse Nordic Curl",
    icon: "🔄", category: "legs", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "Kleknuti, telo pravo, polako se nagnuti unazad koristeći kvadricepse kao kočnicu.",
    desc_en: "Kneel upright, slowly lean backward using quads as a brake. Excellent quad eccentric.",
    muscles: { primary: ["rectus_femoris","vastus_lat","vastus_med"], secondary: ["vastus_int","iliopsoas"] },
  },
  {
    id: "copenhagen_plank",
    sr: "Copenhagen Plank", en: "Copenhagen Plank",
    icon: "📐", category: "legs", difficulty: 6,
    xpWeight: 0.8,
    isHold: true,
    desc_sr: "Bočni plank sa stopalom gornje noge oslonjenoj na povišenu podlogu. Vrhunski aduktorski hold.",
    desc_en: "Side plank with top foot on an elevated surface. Elite adductor isometric exercise.",
    muscles: { primary: ["glute_med","adductors","oblique_int"], secondary: ["transversus","rectus_abdominis","glute_min"] },
  },
  {
    id: "sl_romanian_deadlift",
    sr: "Jednonožni Rumunski Mrtvi Lift", en: "Single Leg Romanian Deadlift",
    icon: "🦢", category: "legs", difficulty: 4,
    xpWeight: 1.5,
    desc_sr: "Naginjanje napred na jednoj nozi bez težine. Hamstrings, ravnoteža i gluteusi.",
    desc_en: "Hinge forward on one leg without weight. Hamstrings, balance and glute focus.",
    muscles: { primary: ["bicep_femoris","semitendinosus","glute_max"], secondary: ["semimembranosus","glute_med","erector_spinae"] },
  },

// ══════════════════════════════════════════════════════════
// CORE - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "reverse_crunch",
    sr: "Reverse Crunch", en: "Reverse Crunch",
    icon: "🔃", category: "core", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Podizanje kukova sa poda — kolena prema grudima. Fokus na donji deo rectus abdominisa.",
    desc_en: "Lifting hips off the floor — knees toward chest. Targets lower rectus abdominis.",
    muscles: { primary: ["rectus_abdominis","iliopsoas"], secondary: ["transversus","oblique_ext"] },
  },
  {
    id: "v_up",
    sr: "V-Up", en: "V-Up",
    icon: "✌️", category: "core", difficulty: 4,
    xpWeight: 1.4,
    desc_sr: "Istovremeno podizanje ruku i nogu ka sredini — telo formira V oblik. Pun core.",
    desc_en: "Simultaneously raise arms and legs toward center — body forms a V shape. Full core.",
    muscles: { primary: ["rectus_abdominis","iliopsoas"], secondary: ["oblique_ext","transversus","rectus_femoris"] },
  },
  {
    id: "bicycle_crunch",
    sr: "Bicycle Crunch", en: "Bicycle Crunch",
    icon: "🚴", category: "core", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Naizmenično privlačenje kolena i rotacija trupa. Odlično za oblique mišiće.",
    desc_en: "Alternating knee drives with trunk rotation. Excellent oblique activator.",
    muscles: { primary: ["oblique_ext","oblique_int","rectus_abdominis"], secondary: ["iliopsoas","rectus_femoris","transversus"] },
  },
  {
    id: "flutter_kicks",
    sr: "Flutter Kicks", en: "Flutter Kicks",
    icon: "🦵", category: "core", difficulty: 3,
    xpWeight: 0.6,
    desc_sr: "Naizmenično podizanje nogu u ležećem položaju niskim amplitudama. Aktivira hip flexors i core.",
    desc_en: "Alternating low-amplitude leg lifts while lying down. Activates hip flexors and core.",
    muscles: { primary: ["iliopsoas","rectus_femoris","rectus_abdominis"], secondary: ["transversus","oblique_ext"] },
  },
  {
    id: "scissor_kicks",
    sr: "Scissor Kicks", en: "Scissor Kicks",
    icon: "✂️", category: "core", difficulty: 3,
    xpWeight: 0.6,
    desc_sr: "Ukrštanje nogu u ležećem položaju slično makaz-ama. Fokus na trbuh i hip flexore.",
    desc_en: "Crossing legs in a scissoring motion while lying down. Targets core and hip flexors.",
    muscles: { primary: ["iliopsoas","rectus_abdominis"], secondary: ["oblique_ext","transversus","rectus_femoris"] },
  },
  {
    id: "russian_twist",
    sr: "Russian Twist", en: "Russian Twist",
    icon: "🌀", category: "core", difficulty: 3,
    xpWeight: 1.0,
    desc_sr: "Rotacija trupa u sedećem položaju sa podignutim nogama. Fokus na oblique mišiće.",
    desc_en: "Trunk rotation in seated position with feet elevated. Focus on oblique muscles.",
    muscles: { primary: ["oblique_ext","oblique_int"], secondary: ["rectus_abdominis","transversus","iliopsoas"] },
  },
  {
    id: "hanging_windshield_wiper",
    sr: "Viseći Brisači", en: "Hanging Windshield Wiper",
    icon: "🌀", category: "core", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Viseći na šipki, rotirati noge od jedne do druge strane poput brisača. Napredni oblique.",
    desc_en: "Hanging from a bar, rotate legs side to side like windshield wipers. Advanced obliques.",
    muscles: { primary: ["oblique_ext","oblique_int","lats"], secondary: ["rectus_abdominis","transversus","iliopsoas"] },
  },
  {
    id: "front_lever_raise",
    sr: "Front Lever Raise", en: "Front Lever Raise",
    icon: "⬆️", category: "core", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Iz dead hang, podizanje tela u front lever poziciju. Vrhunska vežba za core i leđa.",
    desc_en: "From dead hang, raise body to front lever position. Elite core and back exercise.",
    muscles: { primary: ["rectus_abdominis","lats","iliopsoas"], secondary: ["teres_major","oblique_ext","transversus"] },
  },
  {
    id: "lsit_leg_raise",
    sr: "L-Sit Podizanje Nogu", en: "L-Sit Leg Raise",
    icon: "🦵", category: "core", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "Iz L-Sit pozicije, podizanje nogu više. Napredna kompresiona vežba za hip flexore i core.",
    desc_en: "From L-Sit position, raise legs higher. Advanced compression exercise for hip flexors and core.",
    muscles: { primary: ["iliopsoas","rectus_femoris","rectus_abdominis"], secondary: ["transversus","oblique_ext","pec_major_lower"] },
  },
  {
    id: "compression_hold",
    sr: "Compression Hold", en: "Compression Hold",
    icon: "🗜️", category: "core", difficulty: 5,
    xpWeight: 0.7,
    isHold: true,
    desc_sr: "Sedeći ili stojeći, noge prave, pritisnuti stomak prema nogama što je više moguće. Kompresija.",
    desc_en: "Seated or standing, straight legs, compress abdomen toward legs as much as possible.",
    muscles: { primary: ["iliopsoas","rectus_femoris","transversus"], secondary: ["rectus_abdominis","oblique_int"] },
  },
  {
    id: "dead_bug",
    sr: "Dead Bug", en: "Dead Bug",
    icon: "🐛", category: "core", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Ležeći na leđima, naizmenično spuštati suprotne ruke i noge uz zadržavanje kontakta leđa sa tlom.",
    desc_en: "On back, alternately lower opposite arm and leg while keeping lower back pressed to floor.",
    muscles: { primary: ["transversus","rectus_abdominis"], secondary: ["iliopsoas","oblique_int","erector_spinae"] },
  },
  {
    id: "bird_dog",
    sr: "Bird Dog", en: "Bird Dog",
    icon: "🐕", category: "core", difficulty: 2,
    xpWeight: 0.8,
    desc_sr: "Iz četveronožnog položaja, istovremeno ispružiti suprotnu ruku i nogu. Stabilizacija kičme.",
    desc_en: "From quadruped position, simultaneously extend opposite arm and leg. Spine stabilization.",
    muscles: { primary: ["transversus","erector_spinae","glute_max"], secondary: ["rectus_abdominis","delt_posterior","glute_med"] },
  },
  {
    id: "hollow_rock",
    sr: "Hollow Rock", en: "Hollow Rock",
    icon: "🪨", category: "core", difficulty: 4,
    xpWeight: 1.2,
    desc_sr: "U hollow body poziciji, ljuljanje napred-nazad poput stolice za ljuljanje. Aktivan core cijelo vreme.",
    desc_en: "In hollow body position, rock forward and backward like a rocking chair. Core always active.",
    muscles: { primary: ["rectus_abdominis","transversus","iliopsoas"], secondary: ["oblique_ext","rectus_femoris"] },
  },
  {
    id: "arch_hold",
    sr: "Arch Hold", en: "Arch Hold",
    icon: "🌈", category: "core", difficulty: 3,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "Ležeći na stomaku, istovremeno podignuti ruke i noge — supermenova pozicija. Leđa i glutes.",
    desc_en: "Lying on stomach, simultaneously raise arms and legs — superman position. Back and glutes.",
    muscles: { primary: ["erector_spinae","glute_max","trap_lower"], secondary: ["glute_med","delt_posterior","rhomboids"] },
  },
  {
    id: "superman_hold",
    sr: "Superman Hold", en: "Superman Hold",
    icon: "🦸", category: "core", difficulty: 3,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "Ekstremna arc hold pozicija sa maksimalnim ekxtenzijom. Fokus na donji deo leđa.",
    desc_en: "Extreme arch hold with maximum extension. Focus on lower back strength.",
    muscles: { primary: ["erector_spinae","glute_max"], secondary: ["trap_lower","glute_med","delt_posterior"] },
  },

// ══════════════════════════════════════════════════════════
// HOLD - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "active_hang",
    sr: "Active Hang", en: "Active Hang",
    icon: "⚓", category: "hold", difficulty: 2,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "Viseći na šipki sa aktivno povučenim lopaticama (ne pasivni hang). Osnova za sve pull vežbe.",
    desc_en: "Hanging with actively depressed and retracted scapulae (not passive). Foundation for all pull work.",
    muscles: { primary: ["lats","trap_lower","teres_major"], secondary: ["rhomboids","serratus","trap_mid"] },
  },
  {
    id: "scapular_hang",
    sr: "Scapular Hang", en: "Scapular Hang",
    icon: "📏", category: "hold", difficulty: 2,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "Dead hang sa naizmeničnim aktiviranjem i opuštanjem lopatica. Zdravlje ramena.",
    desc_en: "Dead hang alternately activating and relaxing scapulae. Shoulder health exercise.",
    muscles: { primary: ["trap_lower","serratus","lats"], secondary: ["rhomboids","infraspinatus","teres_minor"] },
  },
  {
    id: "tuck_lsit",
    sr: "Tuck L-Sit", en: "Tuck L-Sit",
    icon: "🪑", category: "hold", difficulty: 3,
    xpWeight: 0.5,
    isHold: true,
    desc_sr: "L-Sit sa savijenim kolenima — priprema za puni L-Sit. Fokus na kompresiju i triceps.",
    desc_en: "L-Sit with bent knees — preparation for full L-Sit. Focus on compression and triceps.",
    muscles: { primary: ["iliopsoas","rectus_femoris","tricep_long"], secondary: ["transversus","pec_major_lower","delt_anterior"] },
  },
  {
    id: "adv_tuck_lsit",
    sr: "Advanced Tuck L-Sit", en: "Advanced Tuck L-Sit",
    icon: "🪑", category: "hold", difficulty: 4,
    xpWeight: 0.6,
    isHold: true,
    desc_sr: "L-Sit sa savijenim kolenima, kuk u ravni sa ramenima. Napredna kompresija.",
    desc_en: "L-Sit with bent knees, hips level with shoulders. Advanced compression hold.",
    muscles: { primary: ["iliopsoas","rectus_femoris","tricep_long"], secondary: ["transversus","rectus_abdominis","pec_major_lower"] },
  },
  {
    id: "v_sit",
    sr: "V-Sit", en: "V-Sit",
    icon: "✌️", category: "hold", difficulty: 7,
    xpWeight: 1.0,
    isHold: true,
    desc_sr: "L-Sit sa nogama podignutim iznad horizontale — telo formira V. Vrhunski kompresioni element.",
    desc_en: "L-Sit with legs raised above horizontal — body forms a V. Elite compression element.",
    muscles: { primary: ["iliopsoas","rectus_femoris","rectus_abdominis"], secondary: ["transversus","tricep_long","pec_major_lower"] },
  },
  {
    id: "manna_progression",
    sr: "Manna Progresija", en: "Manna Progression",
    icon: "🌟", category: "hold", difficulty: 9,
    xpWeight: 1.5,
    isHold: true,
    desc_sr: "Najnapredniji kompresioni element — noge iznad glave u sedećem položaju. Vrhunac kalistenikeé.",
    desc_en: "Most advanced compression element — legs above head while seated. Peak calisthenics skill.",
    muscles: { primary: ["iliopsoas","rectus_abdominis","transversus"], secondary: ["rectus_femoris","tricep_long","pec_major_lower"] },
  },
  {
    id: "german_hang",
    sr: "German Hang", en: "German Hang",
    icon: "🔄", category: "hold", difficulty: 4,
    xpWeight: 0.6,
    isHold: true,
    desc_sr: "Viseći iza šipke sa rukama iza leđa. Intenzivno istezanje ramena i pripreme za skin the cat.",
    desc_en: "Hanging behind the bar with arms behind the back. Intense shoulder stretch and skin the cat prep.",
    muscles: { primary: ["delt_anterior","pec_major_upper","bicep_long"], secondary: ["infraspinatus","teres_minor","lats"] },
  },
  {
    id: "ring_support_hold",
    sr: "Ring Support Hold", en: "Ring Support Hold",
    icon: "⭕", category: "hold", difficulty: 4,
    xpWeight: 0.7,
    isHold: true,
    desc_sr: "Oslonac na karikama sa ispruženim rukama. Temelj za sve ring vežbe i RTO.",
    desc_en: "Support hold on rings with straight arms. Foundation for all ring exercises and RTO.",
    muscles: { primary: ["tricep_long","pec_minor","serratus"], secondary: ["delt_anterior","pec_major_lower","transversus"] },
  },
  {
    id: "rto_support_hold",
    sr: "RTO Support Hold", en: "RTO Support Hold",
    icon: "🔄", category: "hold", difficulty: 6,
    xpWeight: 1.0,
    isHold: true,
    desc_sr: "Ring support hold sa karikama okrenutim navani (RTO). Enormno opterećenje pectoralisa i seratusa.",
    desc_en: "Ring support hold with rings turned out (RTO). Enormous pec and serratus loading.",
    muscles: { primary: ["pec_major_lower","serratus","pec_minor"], secondary: ["tricep_long","delt_anterior","infraspinatus"] },
  },
  {
    id: "tuck_back_lever",
    sr: "Tuck Back Lever", en: "Tuck Back Lever",
    icon: "📐", category: "hold", difficulty: 5,
    xpWeight: 0.8,
    isHold: true,
    desc_sr: "Back lever sa savijenim kolenima. Priprema za puni back lever.",
    desc_en: "Back lever with knees bent. Preparation for the full back lever.",
    muscles: { primary: ["lats","teres_major","pec_major_lower"], secondary: ["bicep_long","delt_anterior","rhomboids"] },
  },
  {
    id: "adv_tuck_back_lever",
    sr: "Advanced Tuck Back Lever", en: "Advanced Tuck Back Lever",
    icon: "📐", category: "hold", difficulty: 6,
    xpWeight: 0.9,
    isHold: true,
    desc_sr: "Back lever sa kukovima u ravni sa ramenima. Napredna progresija pre straddle-a.",
    desc_en: "Back lever with hips level with shoulders. Advanced progression before straddle.",
    muscles: { primary: ["lats","teres_major","pec_major_lower"], secondary: ["bicep_long","delt_anterior","rhomboids"] },
  },
  {
    id: "straddle_back_lever",
    sr: "Straddle Back Lever", en: "Straddle Back Lever",
    icon: "✈️", category: "hold", difficulty: 7,
    xpWeight: 1.1,
    isHold: true,
    desc_sr: "Back lever sa nogama rastavljenim u stranu. Između advanced tuck i punog back levera.",
    desc_en: "Back lever with legs spread wide. Intermediate between advanced tuck and full back lever.",
    muscles: { primary: ["lats","teres_major","pec_major_lower"], secondary: ["bicep_long","delt_anterior","erector_spinae"] },
  },

// ══════════════════════════════════════════════════════════
// SKILL - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "crow_pose",
    sr: "Crow Pose", en: "Crow Pose",
    icon: "🐦", category: "skill", difficulty: 4,
    xpWeight: 1.5,
    isHold: true,
    desc_sr: "Balansiranje na rukama sa kolenima oslonjenima na nadlaktice. Ulazna tačka za handstand.",
    desc_en: "Balancing on hands with knees resting on upper arms. Entry point for handstand work.",
    muscles: { primary: ["delt_anterior","tricep_long","pec_minor"], secondary: ["transversus","serratus","rectus_abdominis"] },
  },
  {
    id: "frog_stand",
    sr: "Frog Stand", en: "Frog Stand",
    icon: "🐸", category: "skill", difficulty: 3,
    xpWeight: 1.2,
    isHold: true,
    desc_sr: "Balansiranje sa koljenima oslonjenima na laktove. Uvod u balansiranje na rukama.",
    desc_en: "Balancing with knees resting on bent elbows. Introduction to hand balancing.",
    muscles: { primary: ["delt_anterior","tricep_lateral","pec_minor"], secondary: ["transversus","serratus"] },
  },
  {
    id: "elbow_lever",
    sr: "Elbow Lever", en: "Elbow Lever",
    icon: "⚖️", category: "skill", difficulty: 5,
    xpWeight: 1.8,
    isHold: true,
    desc_sr: "Balansiranje horizontalno sa laktovima u stomaku. Fantastičan trening balansa i snage.",
    desc_en: "Horizontal balance with elbows pressing into abdomen. Great balance and strength skill.",
    muscles: { primary: ["delt_anterior","transversus","serratus"], secondary: ["pec_minor","tricep_lateral","oblique_ext"] },
  },
  {
    id: "headstand",
    sr: "Headstand", en: "Headstand",
    icon: "🙃", category: "skill", difficulty: 3,
    xpWeight: 1.0,
    isHold: true,
    desc_sr: "Balansiranje na glavi i rukama. Temelj za handstand i inverzno kretanje.",
    desc_en: "Balancing on head and hands. Foundation for handstand and inverted movement.",
    muscles: { primary: ["trap_upper","delt_lateral","serratus"], secondary: ["transversus","rectus_abdominis","tricep_long"] },
  },
  {
    id: "press_to_handstand",
    sr: "Press to Handstand", en: "Press to Handstand",
    icon: "🚀", category: "skill", difficulty: 9,
    xpWeight: 3.5,
    desc_sr: "Iz L-sit ili straddle pozicije, presovanje u handstand bez zamaha. Vrhunac snage i kontrole.",
    desc_en: "From L-sit or straddle, press into handstand without kicking. Peak strength and control.",
    muscles: { primary: ["delt_anterior","serratus","pec_minor"], secondary: ["transversus","tricep_long","iliopsoas"] },
  },
  {
    id: "handstand_walk",
    sr: "Handstand Walk", en: "Handstand Walk",
    icon: "🚶", category: "skill", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Hodanje na rukama u handstand poziciji. Zahteva balans, snagu i koordinaciju.",
    desc_en: "Walking on hands in handstand position. Requires balance, strength and coordination.",
    muscles: { primary: ["delt_anterior","serratus","trap_lower"], secondary: ["transversus","pec_minor","tricep_long"] },
  },
  {
    id: "wall_handstand_taps",
    sr: "Handstand Tapšanje uz Zid", en: "Wall Handstand Shoulder Taps",
    icon: "👋", category: "skill", difficulty: 5,
    xpWeight: 1.8,
    desc_sr: "U handstand-u uz zid, naizmenično podizati ruke i tapšati ramena. Priprema za slobodan handstand.",
    desc_en: "In wall handstand, alternately lift hands and tap shoulders. Free handstand prep.",
    muscles: { primary: ["delt_anterior","serratus","trap_lower"], secondary: ["transversus","tricep_long","pec_minor"] },
  },
  {
    id: "front_lever_pull",
    sr: "Front Lever Pull", en: "Front Lever Pull",
    icon: "⬆️", category: "skill", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Iz front lever pozicije, povlačenje šipke prema kukovima. Kombinacija snage i tehnike.",
    desc_en: "From front lever, pull bar toward hips. Combination of strength and technique.",
    muscles: { primary: ["lats","teres_major","rectus_abdominis"], secondary: ["bicep_long","rhomboids","trap_lower"] },
  },
  {
    id: "front_lever_touch",
    sr: "Front Lever Touch", en: "Front Lever Touch",
    icon: "☝️", category: "skill", difficulty: 7,
    xpWeight: 2.5,
    desc_sr: "Iz dead hang-a, kratko dosezanje front lever pozicije i vraćanje. Razvoj eksplozivnog pull-a.",
    desc_en: "From dead hang, briefly reaching front lever position and returning. Explosive pull development.",
    muscles: { primary: ["lats","teres_major"], secondary: ["bicep_long","rectus_abdominis","trap_lower"] },
  },
  {
    id: "back_lever_pull",
    sr: "Back Lever Pull", en: "Back Lever Pull",
    icon: "⬇️", category: "skill", difficulty: 8,
    xpWeight: 3.0,
    desc_sr: "Dinamični pokret iz back lever-a prema gore. Razvija zadnju stranu ramena i leđa.",
    desc_en: "Dynamic movement from back lever upward. Develops posterior shoulder and back.",
    muscles: { primary: ["lats","teres_major","delt_posterior"], secondary: ["bicep_long","rhomboids","trap_mid"] },
  },
  {
    id: "hefesto",
    sr: "Hefesto", en: "Hefesto",
    icon: "⚒️", category: "skill", difficulty: 9,
    xpWeight: 3.5,
    desc_sr: "Rotacija unazad na šipki iz inverted hang-a u skin the cat i povratak samo snagom bicepsa.",
    desc_en: "Backward rotation on bar from inverted hang through skin the cat using only bicep strength.",
    muscles: { primary: ["bicep_long","bicep_short","brachialis"], secondary: ["lats","teres_major","delt_posterior"] },
  },
  {
    id: "iron_cross",
    sr: "Iron Cross", en: "Iron Cross",
    icon: "✝️", category: "skill", difficulty: 10,
    xpWeight: 4.0,
    isHold: true,
    desc_sr: "Ruke potpuno ispružene u stranu na karikama. Jedan od najtežih elemenata u kalistenikomé.",
    desc_en: "Arms fully extended sideways on rings. One of the most demanding elements in calisthenics.",
    muscles: { primary: ["pec_major_upper","pec_major_lower","delt_lateral"], secondary: ["lats","teres_major","serratus"] },
  },
  {
    id: "azarian_cross",
    sr: "Azarian Cross", en: "Azarian Cross",
    icon: "✝️", category: "skill", difficulty: 10,
    xpWeight: 4.5,
    isHold: true,
    desc_sr: "Iron cross sa rukama iznad horizontale. Najtezi gimnasticki element za gornji deo tela.",
    desc_en: "Iron cross with arms above horizontal. The hardest gymnastics upper body element.",
    muscles: { primary: ["delt_lateral","pec_major_upper","serratus"], secondary: ["lats","teres_major","pec_minor"] },
  },
  {
    id: "victorian_press",
    sr: "Victorian Press", en: "Victorian Press",
    icon: "👑", category: "skill", difficulty: 10,
    xpWeight: 4.0,
    desc_sr: "Press iz Victorian Hold pozicije. Možda najteza kalistenička vežba za gornji deo tela.",
    desc_en: "Press from Victorian Hold position. Perhaps the hardest calisthenics upper body exercise.",
    muscles: { primary: ["delt_posterior","teres_major","lats"], secondary: ["tricep_long","serratus","rhomboids"] },
  },
  {
    id: "planche_pushup",
    sr: "Planche Push-Up", en: "Planche Push-Up",
    icon: "🛸", category: "skill", difficulty: 10,
    xpWeight: 4.0,
    desc_sr: "Push-up u punoj planche poziciji. Ultimativna push vežba bez opreme.",
    desc_en: "Push-up in full planche position. The ultimate bodyweight push exercise.",
    muscles: { primary: ["delt_anterior","pec_minor","serratus"], secondary: ["pec_major_upper","tricep_long","transversus"] },
  },
  {
    id: "straddle_planche_pushup",
    sr: "Straddle Planche Push-Up", en: "Straddle Planche Push-Up",
    icon: "🛸", category: "skill", difficulty: 9,
    xpWeight: 3.5,
    desc_sr: "Push-up u straddle planche poziciji. Progresija između tuck i pune planche push-up.",
    desc_en: "Push-up in straddle planche position. Progression between tuck and full planche push-up.",
    muscles: { primary: ["delt_anterior","pec_minor","serratus"], secondary: ["pec_major_upper","tricep_long","transversus"] },
  },
  {
    id: "maltese_hold",
    sr: "Maltese Hold", en: "Maltese Hold",
    icon: "✈️", category: "skill", difficulty: 10,
    xpWeight: 4.5,
    isHold: true,
    desc_sr: "Planche sa rukama izuzetno široko. Jedan od najtežih holdova u kalistenikomé.",
    desc_en: "Planche with arms extremely wide. One of the most demanding holds in calisthenics.",
    muscles: { primary: ["delt_anterior","pec_major_lower","serratus"], secondary: ["pec_minor","transversus","trap_lower"] },
  },
  {
    id: "maltese_press",
    sr: "Maltese Press", en: "Maltese Press",
    icon: "✈️", category: "skill", difficulty: 10,
    xpWeight: 5.0,
    desc_sr: "Push-up iz Maltese Hold pozicije. Možda najteza kalistenička vežba ikada.",
    desc_en: "Push-up from Maltese Hold position. Perhaps the most demanding calisthenics exercise ever.",
    muscles: { primary: ["delt_anterior","pec_major_lower","serratus"], secondary: ["pec_minor","tricep_long","transversus"] },
  },

// ══════════════════════════════════════════════════════════
// CARDIO / CONDITIONING - NEW
// ══════════════════════════════════════════════════════════
  {
    id: "high_knees",
    sr: "High Knees", en: "High Knees",
    icon: "🏃", category: "cardio", difficulty: 2,
    xpWeight: 0.5,
    desc_sr: "Trčanje u mestu sa visokim podizanjem kolena. Odlično za kardio i hip flexore.",
    desc_en: "Running in place with high knee drive. Great for cardio and hip flexors.",
    muscles: { primary: ["iliopsoas","rectus_femoris"], secondary: ["gastrocnemius","glute_max","rectus_abdominis"] },
  },
  {
    id: "jump_rope",
    sr: "Preskakanje Užeta", en: "Jump Rope",
    icon: "🪢", category: "cardio", difficulty: 2,
    xpWeight: 0.4,
    desc_sr: "Preskakanje vijace. Odlično za kardio, koordinaciju i listove.",
    desc_en: "Jumping rope. Excellent for cardio, coordination and calves.",
    muscles: { primary: ["gastrocnemius","soleus"], secondary: ["glute_max","rectus_femoris","delt_anterior"] },
  },
  {
    id: "star_jumps",
    sr: "Star Jumps", en: "Star Jumps",
    icon: "⭐", category: "cardio", difficulty: 2,
    xpWeight: 0.6,
    desc_sr: "Skok sa raskorakom ruku i nogu u obliku zvezde. Jednostavan kardio pokret.",
    desc_en: "Jump spreading arms and legs wide in a star shape. Simple cardio movement.",
    muscles: { primary: ["glute_max","glute_med","vastus_lat"], secondary: ["gastrocnemius","delt_lateral","rectus_femoris"] },
  },
  {
    id: "tuck_jumps",
    sr: "Tuck Jumps", en: "Tuck Jumps",
    icon: "🦘", category: "cardio", difficulty: 4,
    xpWeight: 1.0,
    desc_sr: "Eksplozivni skokovi sa privlačenjem kolena prema grudima. Pliometrika i core.",
    desc_en: "Explosive jumps pulling knees to chest. Plyometrics and core engagement.",
    muscles: { primary: ["glute_max","rectus_femoris","gastrocnemius"], secondary: ["iliopsoas","rectus_abdominis","soleus"] },
  },
  {
    id: "sprint",
    sr: "Sprint", en: "Sprint",
    icon: "⚡", category: "cardio", difficulty: 5,
    xpWeight: 0.8,
    desc_sr: "Trčanje maksimalnom brzinom na kratke distance. Razvija eksplozivnost i snagu nogu.",
    desc_en: "Running at maximum speed over short distances. Develops explosiveness and leg power.",
    muscles: { primary: ["glute_max","bicep_femoris","gastrocnemius"], secondary: ["rectus_femoris","iliopsoas","soleus"] },
  },
  {
    id: "bear_crawl",
    sr: "Bear Crawl", en: "Bear Crawl",
    icon: "🐻", category: "cardio", difficulty: 3,
    xpWeight: 0.8,
    desc_sr: "Kretanje na sve četiri (ruke i prsti nogu) uz zadržavanje horizontalnog trupa.",
    desc_en: "Moving on all fours (hands and toe tips) while keeping torso horizontal.",
    muscles: { primary: ["delt_anterior","tricep_long","rectus_abdominis"], secondary: ["glute_max","rectus_femoris","transversus"] },
  },
  {
    id: "crab_walk",
    sr: "Crab Walk", en: "Crab Walk",
    icon: "🦀", category: "cardio", difficulty: 3,
    xpWeight: 0.8,
    desc_sr: "Kretanje na rukama i nogama sa licem prema gore. Razvija tricepse, zadnja ramena i core.",
    desc_en: "Moving on hands and feet face up. Develops triceps, posterior shoulders and core.",
    muscles: { primary: ["tricep_long","delt_posterior","glute_max"], secondary: ["rectus_abdominis","trap_mid","brachialis"] },
  },
  {
    id: "shuttle_run",
    sr: "Shuttle Run", en: "Shuttle Run",
    icon: "🔁", category: "cardio", difficulty: 4,
    xpWeight: 0.8,
    desc_sr: "Trčanje napred-nazad između dve tačke sa naglim zaustavljanjima i okretima. Agilnost.",
    desc_en: "Running back and forth between two points with sharp stops and turns. Agility training.",
    muscles: { primary: ["glute_max","vastus_lat","gastrocnemius"], secondary: ["bicep_femoris","glute_med","soleus"] },
  },
  {
    id: "skater_jumps",
    sr: "Skater Jumps", en: "Skater Jumps",
    icon: "⛸️", category: "cardio", difficulty: 4,
    xpWeight: 1.0,
    desc_sr: "Bočni skokovi na jednu nogu, imitirajući klizača. Razvija abduktore, gluteuse i ravnotežu.",
    desc_en: "Lateral hops landing on one foot, imitating a skater. Develops abductors, glutes and balance.",
    muscles: { primary: ["glute_med","vastus_lat","gastrocnemius"], secondary: ["glute_max","glute_min","soleus"] },
  },
  {
    id: "burpee_pullup",
    sr: "Burpee Zgib", en: "Burpee Pull-Up",
    icon: "💥", category: "cardio", difficulty: 6,
    xpWeight: 1.8,
    desc_sr: "Burpee kombinovan sa zgibom u jump fazi. Ultimativna full-body kondicionirna vežba.",
    desc_en: "Burpee combined with a pull-up at the jump phase. Ultimate full-body conditioning exercise.",
    muscles: { primary: ["lats","glute_max","pec_major_lower"], secondary: ["bicep_long","rectus_abdominis","gastrocnemius"] },
  },
];

// ── Search ─────────────────────────────────────────────────
export const searchExercises = (query, lang = "sr") => {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();

  const ALIASES = {
    "biceps": ["bicep_long","bicep_short","brachialis"],
    "bicepsi": ["bicep_long","bicep_short","brachialis"],
    "triceps": ["tricep_long","tricep_lateral","tricep_medial"],
    "tricepsi": ["tricep_long","tricep_lateral","tricep_medial"],
    "leđa": ["lats","teres_major","teres_minor","trap_upper","trap_mid","trap_lower","erector_spinae"],
    "ledja": ["lats","teres_major","teres_minor","trap_upper","trap_mid","trap_lower","erector_spinae"],
    "lat": ["lats","teres_major","teres_minor"],
    "lats": ["lats","teres_major","teres_minor"],
    "grudi": ["pec_major_upper","pec_major_lower","pec_minor","serratus"],
    "chest": ["pec_major_upper","pec_major_lower"],
    "pektorali": ["pec_major_upper","pec_major_lower"],
    "ramena": ["delt_anterior","delt_posterior","delt_lateral"],
    "rame": ["delt_anterior","delt_posterior","delt_lateral"],
    "deltoid": ["delt_anterior","delt_posterior","delt_lateral"],
    "shoulders": ["delt_anterior","delt_posterior","delt_lateral"],
    "trapez": ["trap_upper","trap_mid","trap_lower"],
    "traps": ["trap_upper","trap_mid","trap_lower"],
    "trbuh": ["rectus_abdominis","transversus","oblique_ext","oblique_int"],
    "abs": ["rectus_abdominis","transversus","oblique_ext","oblique_int"],
    "trbušnjaci": ["rectus_abdominis","transversus","oblique_ext","oblique_int"],
    "core": ["rectus_abdominis","transversus","oblique_ext","oblique_int"],
    "oblici": ["oblique_ext","oblique_int"],
    "obliques": ["oblique_ext","oblique_int"],
    "noge": ["rectus_femoris","vastus_lat","vastus_med","vastus_int","bicep_femoris","semitendinosus","semimembranosus","glute_max","glute_med","gastrocnemius","soleus"],
    "kvadricepsi": ["rectus_femoris","vastus_lat","vastus_med","vastus_int"],
    "quads": ["rectus_femoris","vastus_lat","vastus_med","vastus_int"],
    "zadnja loža": ["bicep_femoris","semitendinosus","semimembranosus"],
    "hamstrings": ["bicep_femoris","semitendinosus","semimembranosus"],
    "gluteusi": ["glute_max","glute_med","glute_min"],
    "glutes": ["glute_max","glute_med","glute_min"],
    "zadnjica": ["glute_max","glute_med","glute_min"],
    "listovi": ["gastrocnemius","soleus"],
    "calves": ["gastrocnemius","soleus"],
    "podlaktice": ["brachioradialis"],
    "forearms": ["brachioradialis"],
    "holds": [],
    "skill": [],
  };

  let targetIds = ALIASES[q];

  // Special category filters
  if (q === "holds" || q === "hold" || q === "statika" || q === "static") {
    return EXERCISE_DB.filter(ex => ex.isHold);
  }
  if (q === "skill" || q === "skills" || q === "veštine") {
    return EXERCISE_DB.filter(ex => ex.category === "skill");
  }
  if (q === "push" || q === "sklekovi" || q === "guranje") {
    return EXERCISE_DB.filter(ex => ex.category === "push");
  }
  if (q === "pull" || q === "zgibovi" || q === "vlacenje") {
    return EXERCISE_DB.filter(ex => ex.category === "pull");
  }
  if (q === "dips" || q === "propadanja") {
    return EXERCISE_DB.filter(ex => ex.category === "dips");
  }
  if (q === "legs" || q === "noge" || q === "noga") {
    return EXERCISE_DB.filter(ex => ex.category === "legs");
  }
  if (q === "core" || q === "trbuh") {
    return EXERCISE_DB.filter(ex => ex.category === "core");
  }
  if (q === "cardio" || q === "conditioning" || q === "kondicioniranje") {
    return EXERCISE_DB.filter(ex => ex.category === "cardio");
  }

  if (targetIds && targetIds.length > 0) {
    const matched = EXERCISE_DB.filter(ex =>
      targetIds.some(id => ex.muscles.primary.includes(id) || ex.muscles.secondary.includes(id))
    );
    matched.sort((a, b) => {
      const aPri = targetIds.filter(id => a.muscles.primary.includes(id)).length;
      const bPri = targetIds.filter(id => b.muscles.primary.includes(id)).length;
      if (bPri !== aPri) return bPri - aPri;
      return (b.muscles.primary.length + b.muscles.secondary.length) - (a.muscles.primary.length + a.muscles.secondary.length);
    });
    return matched;
  }

  return EXERCISE_DB.filter(ex => {
    const name = lang === "sr" ? ex.sr : ex.en;
    return name.toLowerCase().includes(q) ||
      ex.id.includes(q.replace(/\s/g, "_")) ||
      ex.category.includes(q) ||
      ex.muscles.primary.some(m => MUSCLE_INFO[m]?.[lang]?.toLowerCase().includes(q)) ||
      ex.muscles.secondary.some(m => MUSCLE_INFO[m]?.[lang]?.toLowerCase().includes(q));
  });
};

export const getExerciseById = (id) => EXERCISE_DB.find(ex => ex.id === id);
